inherit_from:
  - .rubocop-main.yml

Style/Documentation:
  Exclude:
    - "app/controllers/**/*"
    - "app/decorators/**/*"
    - "app/helpers/**/*"
    - "app/mailers/**/*"
    - "app/models/**/*"
    - "app/serializers/**/*"
    - "app/policies/**/*"
    - "app/validators/**/*"
    - "db/**/*"
    - "spec/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*"

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "app/admin/**/*"
