source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.0"

gem "active_model_serializers", "~> 0.10.0"
gem "active_skin"
gem "activeadmin"
gem "ancestry", git: "git://github.com/stefankroes/ancestry.git"
gem "bootsnap", ">= 1.1.0", require: false
gem "devise"
gem "devise_token_auth"
gem "faker", git: "https://github.com/stympy/faker.git", branch: "master"
gem "geocoder"
gem "jquery-rails"
gem "mysql2", ">= 0.4.4", "< 0.6.0"
gem "omniauth-google-oauth2"
gem "puma", "~> 3.11"
gem "rack-cors"
gem "rails", "~> 5.2.2"
gem "rails-i18n", "~> 5.1"
gem "rb-readline"

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "pry-byebug"
  gem "rspec-rails", "~> 3.8"
end

group :test do
  gem "database_cleaner"
  gem "dox", require: false
  gem "rails-controller-testing"
  gem "shoulda-matchers", "4.0.0.rc1"
  gem "simplecov", require: false
end

group :development do
  gem "annotate"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "rails-erd"
  gem "rubocop", "~> 0.64.0", require: false
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
